### PR TITLE
Use pkg data

### PR DESCRIPTION
**Pull request by joshuamorton**
This is aggravating. I don't want to explain this change or why it matters.

### CODE REVIEW

**Comment by joshuamorton** [comment]
Yeah, it's a test problem, not a code problem.

**Comment by joshuamorton** [comment]
No no, just this PR (I think), I just mean that the code is good, but
test.sh is the issue.

**Comment by iRapha** [comment]
bump

**Comment by joshuamorton** [comment]
I hate python's packaging system.

**Comment by joshuamorton** [comment]
Merging this even though its still broken because I'm a bad person.

**Pull request merged**
